### PR TITLE
Update CSVReader1.js

### PR DESCRIPTION
**Pull request by pablo-menichini**
Fix call to non-existent function

### CODE REVIEW

**Comment by Bunlong** [comment]
@pablo-menichini Thank you for your contribution. Could I add you to Contributors List ?

**Comment by pablo-menichini** [comment]
You're welcome. Yes, you can add me to contributors list.

**Comment by pabloameni** [comment]
@Bunlong Could you update my username in the contributiors list? Now it's @pabloameni Thanks!

**Comment by Bunlong** [comment]
@pabloameni I updated your username in the contributors list. Thanks!

**Pull request merged**
